services:
  backend:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - cloudsql-proxy

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy
    restart: unless-stopped
    command: >
      --address 0.0.0.0
      --port 5432
      --credentials-file /secrets/service-account-key.json
      ${CLOUDSQL_CONNECTION_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./service-account-key.json:/secrets/service-account-key.json:ro
