"""edit case

Revision ID: 09e3fc2cb491
Revises: 66b76fff9b05
Create Date: 2026-02-02 15:50:16.578546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e3fc2cb491'
down_revision: Union[str, Sequence[str], None] = '66b76fff9b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('immediate_fix', sa.Text(), nullable=True),
    sa.Column('long_term_fix', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_cases_case_id'), 'incident_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_incident_cases_filename'), 'incident_cases', ['filename'], unique=False)
    op.create_index(op.f('ix_incident_cases_id'), 'incident_cases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_cases_id'), table_name='incident_cases')
    op.drop_index(op.f('ix_incident_cases_filename'), table_name='incident_cases')
    op.drop_index(op.f('ix_incident_cases_case_id'), table_name='incident_cases')
    op.drop_table('incident_cases')
    # ### end Alembic commands ###
