"""edit message

Revision ID: 264b7b0dfaa9
Revises: bc4f440c9498
Create Date: 2026-02-06 05:13:57.989646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264b7b0dfaa9'
down_revision: Union[str, Sequence[str], None] = 'bc4f440c9498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('scenario', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_scenario'), 'messages', ['scenario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_scenario'), table_name='messages')
    op.drop_column('messages', 'scenario')
    # ### end Alembic commands ###
