"""update messages for knowledge link

Revision ID: 3e08d1327385
Revises: 7db3c8130f2c
Create Date: 2026-02-03 00:50:15.807640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e08d1327385'
down_revision: Union[str, Sequence[str], None] = '7db3c8130f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('knowledge_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('user', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_knowledge_id'), 'messages', ['knowledge_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'knowledge', ['knowledge_id'], ['id'])
    op.drop_column('messages', 'channel_id')
    op.drop_index(op.f('ix_message_channels_id'), table_name='message_channels')
    op.drop_table('message_channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_channel_id_fkey'), 'messages', 'message_channels', ['channel_id'], ['id'])
    op.drop_index(op.f('ix_messages_knowledge_id'), table_name='messages')
    op.drop_column('messages', 'role')
    op.drop_column('messages', 'user')
    op.drop_column('messages', 'timestamp')
    op.drop_column('messages', 'knowledge_id')
    op.create_table('message_channels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('message_channels_pkey')),
    sa.UniqueConstraint('name', name=op.f('message_channels_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_message_channels_id'), 'message_channels', ['id'], unique=False)
    # ### end Alembic commands ###
