"""edit case

Revision ID: 7db3c8130f2c
Revises: 09e3fc2cb491
Create Date: 2026-02-02 15:59:03.783607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7db3c8130f2c'
down_revision: Union[str, Sequence[str], None] = '09e3fc2cb491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_cases_case_id'), table_name='incident_cases')
    op.drop_index(op.f('ix_incident_cases_filename'), table_name='incident_cases')
    op.drop_index(op.f('ix_incident_cases_id'), table_name='incident_cases')
    op.drop_table('incident_cases')
    op.add_column('knowledge', sa.Column('case_id', sa.String(), nullable=True))
    op.add_column('knowledge', sa.Column('title', sa.String(), nullable=True))
    op.add_column('knowledge', sa.Column('category', sa.String(), nullable=True))
    op.add_column('knowledge', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('knowledge', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('root_cause', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('timeline', sa.JSON(), nullable=True))
    op.add_column('knowledge', sa.Column('immediate_fix', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('long_term_fix', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('knowledge', sa.Column('references', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_knowledge_case_id'), 'knowledge', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_case_id'), table_name='knowledge')
    op.drop_column('knowledge', 'references')
    op.drop_column('knowledge', 'tags')
    op.drop_column('knowledge', 'long_term_fix')
    op.drop_column('knowledge', 'immediate_fix')
    op.drop_column('knowledge', 'timeline')
    op.drop_column('knowledge', 'root_cause')
    op.drop_column('knowledge', 'summary')
    op.drop_column('knowledge', 'severity')
    op.drop_column('knowledge', 'category')
    op.drop_column('knowledge', 'title')
    op.drop_column('knowledge', 'case_id')
    op.create_table('incident_cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('root_cause', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timeline', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('immediate_fix', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('long_term_fix', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_cases_pkey'))
    )
    op.create_index(op.f('ix_incident_cases_id'), 'incident_cases', ['id'], unique=False)
    op.create_index(op.f('ix_incident_cases_filename'), 'incident_cases', ['filename'], unique=False)
    op.create_index(op.f('ix_incident_cases_case_id'), 'incident_cases', ['case_id'], unique=True)
    # ### end Alembic commands ###
