"""edit log

Revision ID: bc4f440c9498
Revises: b7d9a2f1c4a1
Create Date: 2026-02-06 04:32:27.677040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4f440c9498'
down_revision: Union[str, Sequence[str], None] = 'b7d9a2f1c4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_files', sa.Column('scenario', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('log_files_filename_key'), 'log_files', type_='unique')
    op.create_index(op.f('ix_log_files_filename'), 'log_files', ['filename'], unique=False)
    op.create_index(op.f('ix_log_files_scenario'), 'log_files', ['scenario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_files_scenario'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_filename'), table_name='log_files')
    op.create_unique_constraint(op.f('log_files_filename_key'), 'log_files', ['filename'], postgresql_nulls_not_distinct=False)
    op.drop_column('log_files', 'scenario')
    # ### end Alembic commands ###
