"""init_knowledge_schema

Revision ID: c0be9d4e74ab
Revises: 264b7b0dfaa9
Create Date: 2026-02-06 09:28:35.323065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0be9d4e74ab'
down_revision: Union[str, Sequence[str], None] = '9ab08469891c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('report_date', sa.DateTime(), nullable=True))
    op.add_column('knowledge', sa.Column('occurred_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge', sa.Column('report_problem', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('impact_service', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('impact_user', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('impact_data', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('event_details', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('inference_process', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('solution', sa.Text(), nullable=True))
    op.add_column('knowledge', sa.Column('preventive_measures', sa.JSON(), nullable=True))
    op.add_column('knowledge', sa.Column('hidden_risks', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_knowledge_case_id'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_filename'), table_name='knowledge')
    op.create_index(op.f('ix_knowledge_filename'), 'knowledge', ['filename'], unique=True)
    op.create_index(op.f('ix_knowledge_report_date'), 'knowledge', ['report_date'], unique=False)
    op.drop_column('knowledge', 'case_id')
    op.drop_column('knowledge', 'category')
    op.drop_column('knowledge', 'tags')
    op.drop_column('knowledge', 'long_term_fix')
    op.drop_column('knowledge', 'references')
    op.drop_column('knowledge', 'immediate_fix')
    op.drop_column('knowledge', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge', sa.Column('immediate_fix', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge', sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge', sa.Column('long_term_fix', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledge', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('knowledge', sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_knowledge_report_date'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_filename'), table_name='knowledge')
    op.create_index(op.f('ix_knowledge_filename'), 'knowledge', ['filename'], unique=False)
    op.create_index(op.f('ix_knowledge_case_id'), 'knowledge', ['case_id'], unique=False)
    op.drop_column('knowledge', 'hidden_risks')
    op.drop_column('knowledge', 'preventive_measures')
    op.drop_column('knowledge', 'solution')
    op.drop_column('knowledge', 'inference_process')
    op.drop_column('knowledge', 'event_details')
    op.drop_column('knowledge', 'impact_data')
    op.drop_column('knowledge', 'impact_user')
    op.drop_column('knowledge', 'impact_service')
    op.drop_column('knowledge', 'report_problem')
    op.drop_column('knowledge', 'resolved_at')
    op.drop_column('knowledge', 'occurred_at')
    op.drop_column('knowledge', 'report_date')
    # ### end Alembic commands ###
